### ISSUE TITLE
Tracking is not sufficient in the Store.

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/website#1308]
### Expected behavior

Track store purchases to enable us to view average carts, and what system users are buying them from where.
### Actual behavior

There is no flow-tracking in the store.
### To do
- [x] Track store visits
- [x] Track product view
- [ ] Track add to cart
- [x] Track cart visits
- [x] Track checkout visits
- [x] Track completions
- [x] Google Analytics Goal
- [ ] Google Analytics E-commerce Cart Tracking

**Comment by lewisgoddard** [comment]
Adding to cart can wait, it's not key since the cart is always shown afterwards, which we do track.

It's difficult since we immediately navigate away, and pass through another page to one that has no idea what was added.

**Comment by lewisgoddard** [comment]
Wishlisting because the core idea is there.

**Comment by agats** [comment]
Is this ticket still needed? Looks like GA tracking was already added to the shopping flow,
https://github.com/elementary/website/blob/dd8f99d81911c83e2ef81ddb39f9962132eb0e4b/_scripts/pages/download.js#L105-L124

**Comment by btkostner** [comment]
@agats The issue still exists (I think), but we have yet to decide what we want to track and how. Also, the link you gave is GA tracking for homepage downloads, not the store.

**Comment by lewisgoddard** [comment]
If we are moving towards less tracking, this is no longer relevant.
